### ISSUE TITLE
Improve server list and pinger compatability

### ISSUE THREAD

**Issue by ytendx** [NeoProtect/Roadmap#3]
TODO: Add a list of server lists that are uncompatible

**Comment by Squintys** [comment]
https://czech-craft.eu

**Comment by Squintys** [comment]
here are some you could fix too:
https://minecraft-servery.cz
https://minecraft-server-list.cz
https://www.minecraft-list.cz
https://www.minecraftserver.sk

**Comment by Tetanik** [comment]
Add the HotMC bot to the whitelist. ip: 116.203.225.67

Site: https://hotmc.ru/

**Comment by ytendx** [comment]
To finally get to an end here:
We now implemented changes so server lists in general do not get blocked that easily by us and secondly we implemented a global (software-stack wide) whitelist to whitelist them if necessary.
