### ISSUE TITLE
More advanced reselling system

### ISSUE THREAD

**Issue by ytendx** [NeoProtect/Roadmap#32]
Basic features:
- Implement user ranks: Customer, Premium Customer, Business Customer, Admin
- Add user specification at plan model to be able to provide real custom plans
- Only show custom plans to business customers
- Improve coupon code with better limits and security
- Implement backend-force-whitelists to certain domains (Only for business customers)
- Implement list-based frontend visualization in the panel

**Comment by ytendx** [comment]
Most of these sugessted by Jasmeow, thanks

**Comment by Codixer** [comment]
The one and only @JasmeowTheCat :O
