### ISSUE TITLE
Function to deny IP addresses of certain countries inside the neoprotect panel

### ISSUE THREAD

**Issue by liquidman228** [NeoProtect/Roadmap#68]
Add the ability to add some countries to the blacklist

I understand that this might take a long time to do, since there are so many countries, lol. But you can add them gradually

Or make as a field where you can specify a country code, for example 'RU'

Okay, let me be honest. Add a "block Russian IP addresses" button, because they've been attacking me with spam in chat the last few days, hahah

**Comment by pianoman911** [comment]
You'd have to pay attention. This is illegal within the EU. 
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32018R0302

**Comment by pianoman911** [comment]
That means you either have to block the whole EU or not at all. One thought further. There is also talk of service providers. I am not a lawyer. But I think then NeoProtect would have to block the EU as a whole, that makes no sense from an economic point of view. Outside the EU, I don't know the rules.
